/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.0-rc2
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentBrandFlags
 */
export interface CurrentBrandFlags {
    /**
     * 
     * @type {boolean}
     * @memberof CurrentBrandFlags
     */
    policiesBufferedAccessView: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CurrentBrandFlags
     */
    flowsRefreshOthers: boolean;
}

/**
 * Check if a given object implements the CurrentBrandFlags interface.
 */
export function instanceOfCurrentBrandFlags(value: object): value is CurrentBrandFlags {
    if (!('policiesBufferedAccessView' in value) || value['policiesBufferedAccessView'] === undefined) return false;
    if (!('flowsRefreshOthers' in value) || value['flowsRefreshOthers'] === undefined) return false;
    return true;
}

export function CurrentBrandFlagsFromJSON(json: any): CurrentBrandFlags {
    return CurrentBrandFlagsFromJSONTyped(json, false);
}

export function CurrentBrandFlagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentBrandFlags {
    if (json == null) {
        return json;
    }
    return {
        
        'policiesBufferedAccessView': json['policies_buffered_access_view'],
        'flowsRefreshOthers': json['flows_refresh_others'],
    };
}

export function CurrentBrandFlagsToJSON(json: any): CurrentBrandFlags {
    return CurrentBrandFlagsToJSONTyped(json, false);
}

export function CurrentBrandFlagsToJSONTyped(value?: CurrentBrandFlags | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'policies_buffered_access_view': value['policiesBufferedAccessView'],
        'flows_refresh_others': value['flowsRefreshOthers'],
    };
}

