/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.0-rc3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceFacts } from './DeviceFacts';
import {
    DeviceFactsFromJSON,
    DeviceFactsFromJSONTyped,
    DeviceFactsToJSON,
    DeviceFactsToJSONTyped,
} from './DeviceFacts';

/**
 * 
 * @export
 * @interface DeviceFactSnapshot
 */
export interface DeviceFactSnapshot {
    /**
     * 
     * @type {DeviceFacts}
     * @memberof DeviceFactSnapshot
     */
    data: DeviceFacts;
    /**
     * 
     * @type {string}
     * @memberof DeviceFactSnapshot
     */
    connection: string;
    /**
     * 
     * @type {Date}
     * @memberof DeviceFactSnapshot
     */
    readonly created: Date;
    /**
     * 
     * @type {Date}
     * @memberof DeviceFactSnapshot
     */
    readonly expires: Date | null;
}

/**
 * Check if a given object implements the DeviceFactSnapshot interface.
 */
export function instanceOfDeviceFactSnapshot(value: object): value is DeviceFactSnapshot {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('connection' in value) || value['connection'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('expires' in value) || value['expires'] === undefined) return false;
    return true;
}

export function DeviceFactSnapshotFromJSON(json: any): DeviceFactSnapshot {
    return DeviceFactSnapshotFromJSONTyped(json, false);
}

export function DeviceFactSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceFactSnapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'data': DeviceFactsFromJSON(json['data']),
        'connection': json['connection'],
        'created': (new Date(json['created'])),
        'expires': (json['expires'] == null ? null : new Date(json['expires'])),
    };
}

export function DeviceFactSnapshotToJSON(json: any): DeviceFactSnapshot {
    return DeviceFactSnapshotToJSONTyped(json, false);
}

export function DeviceFactSnapshotToJSONTyped(value?: Omit<DeviceFactSnapshot, 'created'|'expires'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DeviceFactsToJSON(value['data']),
        'connection': value['connection'],
    };
}

