/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.5
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceAccessGroupRequest
 */
export interface DeviceAccessGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof DeviceAccessGroupRequest
     */
    name: string;
}

/**
 * Check if a given object implements the DeviceAccessGroupRequest interface.
 */
export function instanceOfDeviceAccessGroupRequest(value: object): value is DeviceAccessGroupRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DeviceAccessGroupRequestFromJSON(json: any): DeviceAccessGroupRequest {
    return DeviceAccessGroupRequestFromJSONTyped(json, false);
}

export function DeviceAccessGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceAccessGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function DeviceAccessGroupRequestToJSON(json: any): DeviceAccessGroupRequest {
    return DeviceAccessGroupRequestToJSONTyped(json, false);
}

export function DeviceAccessGroupRequestToJSONTyped(value?: DeviceAccessGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

