/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const InitialPermissionsModeEnum = {
    User: 'user',
    Role: 'role',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type InitialPermissionsModeEnum = typeof InitialPermissionsModeEnum[keyof typeof InitialPermissionsModeEnum];


export function instanceOfInitialPermissionsModeEnum(value: any): boolean {
    for (const key in InitialPermissionsModeEnum) {
        if (Object.prototype.hasOwnProperty.call(InitialPermissionsModeEnum, key)) {
            if (InitialPermissionsModeEnum[key as keyof typeof InitialPermissionsModeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InitialPermissionsModeEnumFromJSON(json: any): InitialPermissionsModeEnum {
    return InitialPermissionsModeEnumFromJSONTyped(json, false);
}

export function InitialPermissionsModeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitialPermissionsModeEnum {
    return json as InitialPermissionsModeEnum;
}

export function InitialPermissionsModeEnumToJSON(value?: InitialPermissionsModeEnum | null): any {
    return value as any;
}

export function InitialPermissionsModeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): InitialPermissionsModeEnum {
    return value as InitialPermissionsModeEnum;
}

