/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.8.0-rc7
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MutualTLSStageModeEnum = {
    Optional: 'optional',
    Required: 'required',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type MutualTLSStageModeEnum = typeof MutualTLSStageModeEnum[keyof typeof MutualTLSStageModeEnum];


export function instanceOfMutualTLSStageModeEnum(value: any): boolean {
    for (const key in MutualTLSStageModeEnum) {
        if (Object.prototype.hasOwnProperty.call(MutualTLSStageModeEnum, key)) {
            if (MutualTLSStageModeEnum[key as keyof typeof MutualTLSStageModeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MutualTLSStageModeEnumFromJSON(json: any): MutualTLSStageModeEnum {
    return MutualTLSStageModeEnumFromJSONTyped(json, false);
}

export function MutualTLSStageModeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MutualTLSStageModeEnum {
    return json as MutualTLSStageModeEnum;
}

export function MutualTLSStageModeEnumToJSON(value?: MutualTLSStageModeEnum | null): any {
    return value as any;
}

export function MutualTLSStageModeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): MutualTLSStageModeEnum {
    return value as MutualTLSStageModeEnum;
}

