/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.10.0-rc3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorDetail } from './ErrorDetail';
import {
    ErrorDetailFromJSON,
    ErrorDetailFromJSONTyped,
    ErrorDetailToJSON,
    ErrorDetailToJSONTyped,
} from './ErrorDetail';
import type { ContextualFlowInfo } from './ContextualFlowInfo';
import {
    ContextualFlowInfoFromJSON,
    ContextualFlowInfoFromJSONTyped,
    ContextualFlowInfoToJSON,
    ContextualFlowInfoToJSONTyped,
} from './ContextualFlowInfo';

/**
 * Challenge for native browser logout
 * @export
 * @interface NativeLogoutChallenge
 */
export interface NativeLogoutChallenge {
    /**
     * 
     * @type {ContextualFlowInfo}
     * @memberof NativeLogoutChallenge
     */
    flowInfo?: ContextualFlowInfo;
    /**
     * 
     * @type {string}
     * @memberof NativeLogoutChallenge
     */
    component?: string;
    /**
     * 
     * @type {{ [key: string]: Array<ErrorDetail>; }}
     * @memberof NativeLogoutChallenge
     */
    responseErrors?: { [key: string]: Array<ErrorDetail>; };
    /**
     * 
     * @type {string}
     * @memberof NativeLogoutChallenge
     */
    postUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NativeLogoutChallenge
     */
    samlRequest?: string;
    /**
     * 
     * @type {string}
     * @memberof NativeLogoutChallenge
     */
    relayState?: string;
    /**
     * 
     * @type {string}
     * @memberof NativeLogoutChallenge
     */
    providerName?: string;
    /**
     * 
     * @type {string}
     * @memberof NativeLogoutChallenge
     */
    binding?: string;
    /**
     * 
     * @type {string}
     * @memberof NativeLogoutChallenge
     */
    redirectUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NativeLogoutChallenge
     */
    isComplete?: boolean;
}

/**
 * Check if a given object implements the NativeLogoutChallenge interface.
 */
export function instanceOfNativeLogoutChallenge(value: object): value is NativeLogoutChallenge {
    return true;
}

export function NativeLogoutChallengeFromJSON(json: any): NativeLogoutChallenge {
    return NativeLogoutChallengeFromJSONTyped(json, false);
}

export function NativeLogoutChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NativeLogoutChallenge {
    if (json == null) {
        return json;
    }
    return {
        
        'flowInfo': json['flow_info'] == null ? undefined : ContextualFlowInfoFromJSON(json['flow_info']),
        'component': json['component'] == null ? undefined : json['component'],
        'responseErrors': json['response_errors'] == null ? undefined : json['response_errors'],
        'postUrl': json['post_url'] == null ? undefined : json['post_url'],
        'samlRequest': json['saml_request'] == null ? undefined : json['saml_request'],
        'relayState': json['relay_state'] == null ? undefined : json['relay_state'],
        'providerName': json['provider_name'] == null ? undefined : json['provider_name'],
        'binding': json['binding'] == null ? undefined : json['binding'],
        'redirectUrl': json['redirect_url'] == null ? undefined : json['redirect_url'],
        'isComplete': json['is_complete'] == null ? undefined : json['is_complete'],
    };
}

export function NativeLogoutChallengeToJSON(json: any): NativeLogoutChallenge {
    return NativeLogoutChallengeToJSONTyped(json, false);
}

export function NativeLogoutChallengeToJSONTyped(value?: NativeLogoutChallenge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'flow_info': ContextualFlowInfoToJSON(value['flowInfo']),
        'component': value['component'],
        'response_errors': value['responseErrors'],
        'post_url': value['postUrl'],
        'saml_request': value['samlRequest'],
        'relay_state': value['relayState'],
        'provider_name': value['providerName'],
        'binding': value['binding'],
        'redirect_url': value['redirectUrl'],
        'is_complete': value['isComplete'],
    };
}

