/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.2.0-rc2
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedSettingsRequestFlags
 */
export interface PatchedSettingsRequestFlags {
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSettingsRequestFlags
     */
    enterpriseAuditIncludeExpandedDiff: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSettingsRequestFlags
     */
    policiesBufferedAccessView: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSettingsRequestFlags
     */
    flowsRefreshOthers: boolean;
}

/**
 * Check if a given object implements the PatchedSettingsRequestFlags interface.
 */
export function instanceOfPatchedSettingsRequestFlags(value: object): value is PatchedSettingsRequestFlags {
    if (!('enterpriseAuditIncludeExpandedDiff' in value) || value['enterpriseAuditIncludeExpandedDiff'] === undefined) return false;
    if (!('policiesBufferedAccessView' in value) || value['policiesBufferedAccessView'] === undefined) return false;
    if (!('flowsRefreshOthers' in value) || value['flowsRefreshOthers'] === undefined) return false;
    return true;
}

export function PatchedSettingsRequestFlagsFromJSON(json: any): PatchedSettingsRequestFlags {
    return PatchedSettingsRequestFlagsFromJSONTyped(json, false);
}

export function PatchedSettingsRequestFlagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSettingsRequestFlags {
    if (json == null) {
        return json;
    }
    return {
        
        'enterpriseAuditIncludeExpandedDiff': json['enterprise_audit_include_expanded_diff'],
        'policiesBufferedAccessView': json['policies_buffered_access_view'],
        'flowsRefreshOthers': json['flows_refresh_others'],
    };
}

export function PatchedSettingsRequestFlagsToJSON(json: any): PatchedSettingsRequestFlags {
    return PatchedSettingsRequestFlagsToJSONTyped(json, false);
}

export function PatchedSettingsRequestFlagsToJSONTyped(value?: PatchedSettingsRequestFlags | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterprise_audit_include_expanded_diff': value['enterpriseAuditIncludeExpandedDiff'],
        'policies_buffered_access_view': value['policiesBufferedAccessView'],
        'flows_refresh_others': value['flowsRefreshOthers'],
    };
}

