/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.4
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedDeviceAccessGroupRequest
 */
export interface PatchedDeviceAccessGroupRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedDeviceAccessGroupRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the PatchedDeviceAccessGroupRequest interface.
 */
export function instanceOfPatchedDeviceAccessGroupRequest(value: object): value is PatchedDeviceAccessGroupRequest {
    return true;
}

export function PatchedDeviceAccessGroupRequestFromJSON(json: any): PatchedDeviceAccessGroupRequest {
    return PatchedDeviceAccessGroupRequestFromJSONTyped(json, false);
}

export function PatchedDeviceAccessGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDeviceAccessGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PatchedDeviceAccessGroupRequestToJSON(json: any): PatchedDeviceAccessGroupRequest {
    return PatchedDeviceAccessGroupRequestToJSONTyped(json, false);
}

export function PatchedDeviceAccessGroupRequestToJSONTyped(value?: PatchedDeviceAccessGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

