/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.0-rc2
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestedBy
 */
export interface RequestedBy {
    /**
     * 
     * @type {number}
     * @memberof RequestedBy
     */
    readonly pk: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof RequestedBy
     */
    username: string;
}

/**
 * Check if a given object implements the RequestedBy interface.
 */
export function instanceOfRequestedBy(value: object): value is RequestedBy {
    if (!('pk' in value) || value['pk'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function RequestedByFromJSON(json: any): RequestedBy {
    return RequestedByFromJSONTyped(json, false);
}

export function RequestedByFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestedBy {
    if (json == null) {
        return json;
    }
    return {
        
        'pk': json['pk'],
        'username': json['username'],
    };
}

export function RequestedByToJSON(json: any): RequestedBy {
    return RequestedByToJSONTyped(json, false);
}

export function RequestedByToJSONTyped(value?: Omit<RequestedBy, 'pk'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

