/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.10.0-rc3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SAMLProviderLogoutMethodEnum = {
    FrontchannelIframe: 'frontchannel_iframe',
    FrontchannelNative: 'frontchannel_native',
    Backchannel: 'backchannel',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type SAMLProviderLogoutMethodEnum = typeof SAMLProviderLogoutMethodEnum[keyof typeof SAMLProviderLogoutMethodEnum];


export function instanceOfSAMLProviderLogoutMethodEnum(value: any): boolean {
    for (const key in SAMLProviderLogoutMethodEnum) {
        if (Object.prototype.hasOwnProperty.call(SAMLProviderLogoutMethodEnum, key)) {
            if (SAMLProviderLogoutMethodEnum[key as keyof typeof SAMLProviderLogoutMethodEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SAMLProviderLogoutMethodEnumFromJSON(json: any): SAMLProviderLogoutMethodEnum {
    return SAMLProviderLogoutMethodEnumFromJSONTyped(json, false);
}

export function SAMLProviderLogoutMethodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SAMLProviderLogoutMethodEnum {
    return json as SAMLProviderLogoutMethodEnum;
}

export function SAMLProviderLogoutMethodEnumToJSON(value?: SAMLProviderLogoutMethodEnum | null): any {
    return value as any;
}

export function SAMLProviderLogoutMethodEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SAMLProviderLogoutMethodEnum {
    return value as SAMLProviderLogoutMethodEnum;
}

